services:
  app:
    build: ./backend
    container_name: laravel_rede_parcerias
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    networks:
      - rede_parcerias

  webserver:
    image: nginx:latest
    container_name: nginx_rede_parcerias
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - rede_parcerias

  db:
    image: mysql:8.0
    container_name: db_rede_parcerias
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: redeparcerias
      MYSQL_USER: redeparcerias
      MYSQL_PASSWORD: redeparcerias
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rede_parcerias

networks:
  rede_parcerias:
    driver: bridge

volumes:
  db_data:
